import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { useState } from "react";
import ConnectMetamask from "../components/ConnectMetamask";
import useLsystem from "../hook/lsystem.hook";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // login is a boolean that is set to true if the user has connected their metamask

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-300 w-screen h-screen flex flex-col justify-center items-center">
        <Link className="p-2 bg-slate-300 text-5xl" href="/plant">
          plant
        </Link>
      </main>
    </>
  );
}
